// app/labor-cost/page.tsx — add "Labor Cost" to the existing sidebar.
// Uses the existing Supabase public/anon client from the dashboard if available.
'use client';
import {useEffect,useState} from 'react';
type Row={month:string;revenue:number;controllable_labor_cost:number;labor_cost_pct:number;internal_target_pct:number;franchise_band_low:number;franchise_band_high:number};
export default function LaborCostPage(){
 const [rows,setRows]=useState<Row[]>([]); const [growth,setGrowth]=useState(50);
 useEffect(()=>{fetch('/api/labor-cost').then(r=>r.ok?r.json():[]).then(setRows)},[]);
 const x=rows.at(-1); const pct=x?.labor_cost_pct??0; const status=pct>=.10&&pct<=.18?'Within band':'Outside band';
 return <main className="min-h-screen bg-[#f6f3ed] text-[#162331] p-6"><div className="mx-auto max-w-7xl space-y-5">
  <header className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#d86b32]">Topsail Steamer · Anna Maria Island</p><h1 className="mt-1 text-3xl font-bold">Labor Cost</h1><p className="text-sm text-slate-600">Homebase payroll + Clover net sales · tips excluded</p></div><a href="/labor-cost/upload" className="rounded-xl bg-[#d86b32] px-4 py-2 text-sm font-semibold text-white">Upload payroll CSV</a></header>
  <section className="grid gap-4 md:grid-cols-4">{[['Labor Cost %',`${(pct*100).toFixed(1)}%`,'Internal target 13%'],['Net Sales',`$${(x?.revenue??0).toLocaleString()}`,'Clover'],['Controllable Cost',`$${(x?.controllable_labor_cost??0).toLocaleString()}`,'Wages + taxes + fees'],['Status',status,'Franchise band 10–18%']].map(([a,b,c])=><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" key={a as string}><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{a}</div><div className="mt-2 text-2xl font-bold">{b}</div><div className="mt-1 text-xs text-slate-500">{c}</div></div>)}</section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Monthly Labor Trend</h2><p className="text-xs text-slate-500">13% target · 10–18% franchise reference band</p><div className="mt-5 space-y-3">{rows.map(r=><div className="grid grid-cols-[90px_1fr_70px] items-center gap-3 text-sm" key={r.month}><span>{r.month.slice(0,7)}</span><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#d86b32]" style={{width:`${Math.min(100,r.labor_cost_pct*400)}%`}}/></div><b className="text-right">{(r.labor_cost_pct*100).toFixed(1)}%</b></div>)}</div></section>
  <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Growth & Hours Plan</h2><p className="mt-1 text-sm text-slate-500">Editable YoY planning assumption; default 50% follows the source tracker.</p><div className="mt-5 flex items-center gap-4"><input className="w-full" type="range" min="0" max="100" value={growth} onChange={e=>setGrowth(+e.target.value)}/><b>{growth}%</b></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">Target</span><div className="font-semibold">13%</div></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">Band</span><div className="font-semibold">10–18%</div></div></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Employee Detail</h2><p className="mt-1 text-sm text-slate-500">Show employee_labor_detail here; keep the dashboard summary compact and link to the full breakdown.</p></div></section>
 </div></main>
}